name: C/C++ CI

on:
  push:
    branches: [ "main", "patch-1" ]
  pull_request:
    branches: [ "main", "patch-1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make everything
      run: ./build.sh
